### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by pviana87** [reven/ngx-niceindex#3]
Hello, I download and configure niceindex in directory "/etc/apache2/". When I access my webpage in nginx, page return error 500! 

I finded this error in log, see you:

> runtime error: file /etc/apache2/.niceindex/niceindex.xslt line 12 element value-of
> **Variable 'dir' has not been declared.**
> xmlXPathCompiledEval: evaluation failed
> runtime error: file /etc/apache2/.niceindex/niceindex.xslt **line 12** element value-of
> XPath evaluation returned no result.

regards

**Comment by reven** [comment]
Hey Pedro,

First line of the readme:

> 
> ngx-niceindex
> 
> Customizable directory indexes for **nginx** without index modules

Enfasis added by me. This doesn't work with Apache.
